### ISSUE TITLE
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'yes' is undefined

### ISSUE THREAD

**Issue by dafelipe130** [robertdebock/ansible-role-restore#1]
**Describe the bug**
Task failure in _select latest_file in found_files_

**To Reproduce**
1. Install latest version of role (2.1.0 at the time of writing)
2. Run role
3. Receive error 

**Expected behavior**
No errors

**Error**
TASK [robertdebock.restore : select latest_file in found_files] **************************************************************************************
fatal: [ansible-sandbox.dev.acme.com]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'yes' is undefined\n\nThe error appears to have been in '/Users/dfelipe/.ansible/roles/robertdebock.restore/tasks/object.yml': line 10, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: select latest_file in found_files\n  ^ here\n"}

**Environment**
- Control node OS: Darwin 17.3.0
- Control node Ansible version: 2.7.10
- Managed node OS: CentOS 7

**Additional context**

**Comment by robertdebock** [comment]
Here too, thanks @dafelipe130, I've confirmed the issue and will change tests and the role itself to fix the problem.

**Comment by robertdebock** [comment]
It seems this issue has been resolved.
