### ISSUE TITLE
Make sure the required command to extract the file is installed. Command \"/bin/gtar\" found no files in archive. Command \"unzip\" not found. Command \"/bin/gtar\" could not handle archive."}

### ISSUE THREAD

**Issue by dafelipe130** [robertdebock/ansible-role-restore#2]
**Describe the bug**
Failure on task _unarchive directory object_

**To Reproduce**
1. Run this role:
2. See error

**Expected behavior**
No errors

**Error**
TASK [robertdebock.restore : unarchive directory object] *********************************************************************************************
fatal: [ansible-sandbox.dev.acme.com]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/home/dfelipe/.ansible/tmp/ansible-tmp-1574355421.4064481-242245858911432/source\". Make sure the required command to extract the file is installed. Command \"/bin/gtar\" found no files in archive. Command \"unzip\" not found. Command \"/bin/gtar\" could not handle archive."}

**Environment**
- Control node OS: Darwin 17.3.0
- Control node Ansible version: 2.7.10
- Managed node OS: CentOS 7

**Additional context**

**Comment by robertdebock** [comment]
Thanks @dafelipe130, I guess I missed a dependency and a test. I'll work on it.

**Comment by robertdebock** [comment]
Meanwhile, a role [core_dependencies](https://galaxy.ansible.com/robertdebock/core_dependencies) has been released to solve this issue.

Thanks for your feedback!
